version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Upload Coverage to CodeClimate
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?
    environment:
      CC_TEST_REPORTER_ID: your-codeclimate-test-reporter-id

workflows:
  version: 2
  test:
    jobs:
      - test
